name = "spica_benchmarks"
description = "Benchmarks for the Spica library"
version = "0.1.0-dev"

authors = ["Peter Chapin"]
maintainers = ["Peter Chapin <spicacality@kelseymountain.org>"]
maintainers-logins = ["pchapin"]

executables = ["spica_benchmarks"]

[build-switches]
"*".style_checks = "No"

[[depends-on]]
spica = "*"

[[pins]]
spica = { path = ".." }
